# This is the configuration used to check the rubocop source code.
# For list of cops 'https://github.com/bbatsov/rubocop/tree/master/config'

require: rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - config/**/*
    - Guardfile
    - bin/*
    - db/**/*
    - vendor/bundle/**/*

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Performance/CollectionLiteralInLoop:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
