version: '3.1'

services:

  hackerspace3:
    image: govhackau/hackerspace3:ruby2.7
    build: .
    env_file: .env
    ports:
      - 3000:3000
    restart: always

  postgres:
    image: postgres:12.1
    env_file: .env
    volumes:
      - pg_db:/var/lib/postgresql/data
    restart: always

volumes:
  pg_db:
