version: '3.1'

services:

  hackerspace3:
    build: .
    depends_on:
      - postgres
    env_file: .env
    image: govhackau/hackerspace3
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app

  postgres:
    env_file: .env
    image: postgres:12.1
    ports:
      - "5432:5432"
    volumes:
      - pg_db:/var/lib/postgresql/data

volumes:
  pg_db:
